# -*- coding: utf-8 -*-
"""t1_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17au_OgL_2TL7B8R7MTG0gZhcIoR-3mib

## Exploratory Data Analysis (EDA): Impactos no NPS e Jornada do Cliente
Autor: Giusepe Lopes

Contexto: Análise de uma base de e-commerce com 2.500 registros para identificar os principais detratores da experiência do cliente e fatores de risco para a recompra.

1. Objetivos da Análise

    Cálculo do NPS Resultante: Determinar o Net Promoter Score atual da base.

    Identificação de Atrito: Analisar a correlação entre atrasos na entrega, número de reclamações e o tempo de atendimento com a nota de recomendação.

    Segmentação de Comportamento: Comparar o perfil de clientes promotores e detratores.

    Impacto no Negócio: Mensurar como falhas operacionais reduzem a taxa de recompra em 30 dias.

2. Engenharia de Variáveis (Feature Engineering)

    Para aprofundar o estudo, foram criadas as seguintes categorias:

       *is_detractor*: Segmentação binária para notas de NPS abaixo de 7.

        *tenure_category*: Classificação do tempo de casa (Curto, Médio, Longo).

        *delay_category*: Faixas de atraso (No Prazo, 1 dia, 2-3 dias, etc.).

        *delivery_commit_days*: Cálculo da promessa original de entrega.

        *customer_service_category*: Frequência de contatos com o suporte.

3. Principais Insights e Metodologias

    Fatores Críticos: Identificou-se forte correlação negativa entre o NPS e as variáveis delivery_delay_days, complaints_count e resolution_time_days.

    Taxa de Recompra: A análise revelou uma queda drástica na fidelização conforme os dias de atraso aumentam (clientes com 7+ dias de atraso apresentam 0% de taxa de recompra).

    Atendimento: Constatou-se que a resolução no primeiro contato é vital; a partir do segundo contato, o cliente tende a se tornar um detrator, independentemente da solução.

## Importação de libraries
"""

import pandas as pd
import numpy as np
import seaborn as sns
from scipy import stats
import plotly.express as px
from scipy.stats import kruskal
import matplotlib.pyplot as plt

"""## Carga da base de dados"""

df_nps = pd.read_csv("../data/desafio_nps_fase_1.csv")
df_nps.head()

# Verificando valores únicos por coluna
df_nps.nunique()

# Verificando os tipos de dados por coluna. Apenas 'customer_region' sendo armazenado como string.
df_nps.info()

# Verificando se a base possui valores nulos.
df_nps.isnull().sum()

df_nps.describe()

"""Constatações iniciais:


*   19 colunas
*   2500 registros

*   Sem valores nulos
*   Tratam-se de pedidos de 2500 clientes diferentes, customer_id não se repetem na base de dados.

## Distribuição da variável alvo
"""

# Plota o histograma da variavel nps_score, para verificarmos sua distribuição.
px.histogram(df_nps, x='nps_score',nbins=50).show()

# Função para cálculo do teste Shapiro Wilk, para confirmação de distribuição não normal
def shap_wilk_test(target_column):
  """
  Recebe a coluna de um Dataframe e calcula o teste Shapiro Wilk para ela, considerando alpha=0.05 .
  Imprime o resultado e interpretação.
  """
  statistic, p_value = stats.shapiro(target_column)

  print(f"Statistic: {statistic}, p-value: {p_value}")

  alpha = 0.05
  if p_value > alpha:
      print("Amostra parece Gaussiana (falha em rejeitar H0)")
  else:
      print("Amostra não parece Gaussiana (rejeita H0)")

# Executando o teste para a variável nps_score
shap_wilk_test(df_nps['nps_score'])

"""**Podemos perceber que a variável não possui uma distribuição normal**

## Cálculo do NPS resultante

#### ((Number of Promoters - Number of Detractors) / Total Responses) * 100.00
"""

def resulting_nps(full_df, df_promoters, df_detractors):
  '''
  Função para cálculo do NPS resultante.
  Recebe o Dataframe com todos os registros, um apenas com os promotores e outro apenas com os detratores.
  Retorna o valor de NPS resultante.
  '''
  return ((len(df_promoters) - len(df_detractors))/ len(full_df)) * 100

# Separação dos promotores presentes na base
promoters = df_nps[df_nps['nps_score'] >= 9.0]
promoters.describe()

# Separação dos detratores presentes na base
detractors = df_nps[df_nps['nps_score'] < 7.0]
detractors.describe()

# Order value acumulado promotores vs detratores
print("order_value acumulado dos promotores da marca = " + str(promoters['order_value'].sum()))
print("order_value acumulado dos detratores da marca = " + str(detractors['order_value'].sum()))

# Proporção de detratores para promotores na base de dados.
print("Proporção de detratores para promotores = " + str((len(detractors)) / (len(promoters))))

# Calculo do NPS resultante
print("NPS resultante = " + str(resulting_nps(df_nps, promoters, detractors)))

"""## Novas variáveis"""

# Nova coluna para classificar detratores e não detratores
df_nps['is_detractor'] = (df_nps['nps_score'] < 7.0)

# Nova coluna para identificar pedidos com reclamações
df_nps['has_complaints'] = (df_nps['complaints_count'] > 0)

# Categorias para tempo de relacionamento.
bins = [-1, 36, 60, 300]
labels = ['Curto', 'Médio', 'Longo']
df_nps['tenure_category'] = pd.cut(df_nps['customer_tenure_months'], bins=bins, labels=labels)

# Nova coluna para identificar pedidos atrasados.
df_nps['delayed'] = df_nps['delivery_delay_days'] > 0

# Variável categorica para os atrasos de entrega.
bins = [-1, 0, 1, 3, 7, 30]
labels = ['No Prazo', '1 dia', '2-3 dias', '4-7 dias', '7+ dias']
df_nps['delay_category'] = pd.cut(df_nps['delivery_delay_days'], bins=bins, labels=labels)

# Criando uma nova coluna para armazenar o previsão de entrega original, em dias
df_nps['delivery_commit_days'] = df_nps['delivery_time_days'] - df_nps['delivery_delay_days']

# Variável categorica para promessa original de entrega.
bins = [0, 1, 3, 7, 30]
labels = ['1 dia', '2-3 dias', '4-7 dias', '7+ dias']
df_nps['delivery_commit_category'] = pd.cut(df_nps['delivery_commit_days'], bins=bins, labels=labels)

# Criando categorias para análise de atendimento ao cliente
df_nps['contacted_support'] = df_nps['customer_service_contacts'] > 0
bins = [-1, 0, 1, 3, 30]
labels = ['0 contatos', '1 contato', '2-3 contatos', '4+ contatos']
df_nps['customer_service_category'] = pd.cut(df_nps['customer_service_contacts'], bins=bins, labels=labels)

"""#### order_value x detratores"""

sns.boxplot(x='is_detractor', y='order_value', data=df_nps)
plt.title('Boxplot order_value para detratores')
plt.xlabel('Detrator')
plt.ylabel('Valor da compra')
plt.show()

"""#### nps_score x detratores"""

sns.boxplot(x='is_detractor', y='nps_score', data=df_nps)
plt.title('Boxplot nps_score para detratores')
plt.xlabel('Detrator')
plt.show()

"""#### Análise de perfil detratores x promotores"""

# Descrição de perfil dos promotores
promoters[['customer_age', 'customer_tenure_months', 'order_value', 'items_quantity', 'payment_installments', 'discount_value', 'delivery_delay_days', 'delivery_attempts', 'customer_service_contacts', 'complaints_count', 'resolution_time_days', 'repeat_purchase_30d']].describe()

# Descrição de perfil dos detratores
detractors[['customer_age', 'customer_tenure_months', 'order_value', 'items_quantity', 'payment_installments', 'discount_value', 'delivery_delay_days', 'delivery_attempts', 'customer_service_contacts', 'complaints_count', 'resolution_time_days', 'repeat_purchase_30d']].describe()

"""#### Recompra"""

# Verificando a taxa de recompra geral do negócio
print('Taxa de recompra atual: ' + str((df_nps['repeat_purchase_30d'].sum() / df_nps['customer_id'].count()) * 100) + '%')

# Total de detratores que recompraram nos últimos 30 dias.
print("Total de detratores que recompraram nos últimos 30 dias = " + str(df_nps[df_nps["is_detractor"] == True]['repeat_purchase_30d'].sum()))

"""#### Top 10 pedidos de maior valor"""

# Top 10 pedidos de maior valor.
df_nps.sort_values(by='order_value', ascending=False).head(10)

"""#### Detratores por categoria de relacionamento"""

# Total de detratores por categoria de relacionamento.
df_nps[df_nps['is_detractor'] == True].groupby('tenure_category')['customer_id'].count()

"""1082 clientes com relacionamento de mais de 60 meses (5 anos) presentes no grupo de detratores.

#### NPS detratores x tempo de relacionamento
"""

sns.boxplot(x='tenure_category', y='nps_score', data=df_nps[df_nps['is_detractor'] == True])
plt.title('Boxplot NPS detratores por tempo de relacionamento')
plt.xlabel('Tempo de relacionamento')
plt.show()

"""## Correlação com a variável alvo"""

df_nps.dtypes

# Cria um dataframe de trabalho apenas com as variáveis numéricas da base.
df_nps_num = df_nps.drop(labels=['customer_region', 'is_detractor', 'has_complaints', 'tenure_category', 'delayed', 'delay_category', 'delivery_commit_category', 'contacted_support', 'customer_service_category'], axis=1)

# Calcula a matriz de correlação para as variáveis numéricas.
corr_matrix = df_nps_num.corr()

# Reduz corr_matrix apenas para correlações com a variável alvo.
nps_corr = corr_matrix[['nps_score']].sort_values(ascending=False, by='nps_score')
nps_corr

# Constrói e plota o gráfico de mapa de calor correspondente às correlações com nps_score.
plt.figure(figsize=(6,6))
sns.heatmap(nps_corr, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Matriz de correlação nps_score')
plt.show()

# Média das variáveis correlacionadas negativamente, para promotores e detratores.
df_nps.groupby('is_detractor')[['delivery_delay_days', 'complaints_count', 'resolution_time_days']].mean()

"""## Segmentação do NPS resultante a partir das características que contribuem mais negativamente"""

no_complaints_delay_p = promoters[(promoters['complaints_count'] == 0) & (promoters['delivery_delay_days'] == 0)]
no_complaints_delay_d = detractors[(detractors['complaints_count'] == 0) & (detractors['delivery_delay_days'] == 0)]

print("NPS resultante para pedidos sem reclamações e sem atraso: " + str(resulting_nps(df_nps, no_complaints_delay_p, no_complaints_delay_d)))

complaints_only_p = promoters[(promoters['complaints_count'] > 0) & (promoters['delivery_delay_days'] == 0)]
complaints_only_d = detractors[(detractors['complaints_count'] > 0) & (detractors['delivery_delay_days'] == 0)]

print("NPS resultante para pedidos apenas com reclamações: " + str(resulting_nps(df_nps, complaints_only_p, complaints_only_d)))

delay_only_p = promoters[(promoters['complaints_count'] == 0) & (promoters['delivery_delay_days'] > 0)]
delay_only_d = detractors[(detractors['complaints_count'] == 0) & (detractors['delivery_delay_days'] > 0)]

print("NPS resultante para pedidos apenas com atraso: " + str(resulting_nps(df_nps, delay_only_p, delay_only_d)))

complaints_delay_p = promoters[(promoters['complaints_count'] > 0) & (promoters['delivery_delay_days'] > 0)]
complaints_delay_d = detractors[(detractors['complaints_count'] > 0) & (detractors['delivery_delay_days'] > 0)]

print("NPS resultante para pedidos com reclamações e atraso: " + str(resulting_nps(df_nps, complaints_delay_p, complaints_delay_d)))

"""## Cruzamento de scores CSAT vs NPS"""

plt.figure(figsize=(10, 8))

# Scatterplot adicionando um pequeno jitter para melhor visualização
sns.regplot(data=df_nps, x='csat_internal_score', y='nps_score', fit_reg=False, scatter_kws={'alpha':0.6, 's':80, 'color':'teal'},x_jitter=0.2, y_jitter=0.2)

# Linhas de corte dos quadrantes. Usamos 7 para CSAT e 8 para NPS como "sucesso"
plt.axhline(y=8, color='red', linestyle='--', alpha=0.6, label='Corte NPS (Promotores)')
plt.axvline(x=7, color='blue', linestyle='--', alpha=0.6, label='Corte CSAT (Satisfeitos)')

# Legendas do gráfico.
plt.title('Cruzamento CSAT vs NPS')
plt.xlabel('CSAT')
plt.ylabel('NPS')
plt.legend(loc='lower right')

plt.tight_layout()
plt.show()

"""Maior concentração de clientes está abaixo das linhas de corte CSAT & NPS, detratores totais.

## Análise de atraso na entrega
"""

df_delayed_delivery = df_nps[df_nps['delayed'] == True]
df_ontime_delivery = df_nps[df_nps['delayed'] == False]

# Total de pedidos entregues com atraso
print("Total de pedidos entregues com atraso = " + str(len(df_delayed_delivery)))

# Total de pedidos entregues em tempo.
print("Total de pedidos entregues em tempo = " + str(len(df_ontime_delivery)))

# Grafico de barras para representar total de pedidos em atraso.
bar_graphic = sns.barplot(data = df_nps.groupby('delayed')['customer_id'].count().reset_index(), x = 'delayed', y='customer_id')
bar_graphic.bar_label(bar_graphic.containers[0])
plt.title('Total de pedidos entregues em tempo vs. atrasados')
plt.xlabel('Entrega atrasada')
plt.ylabel('Total de pedidos')
plt.show()

# Estatísticas descritivas do NPS para pedidos com atraso na entrega
df_delayed_delivery['nps_score'].describe()

# Estatísticas descritivas do NPS para pedidos com entrega dentro do prazo
df_ontime_delivery['nps_score'].describe()

# Boxplot do NPS entrega em tempo X atrasada.
sns.boxplot(x='delayed', y='nps_score', data=df_nps)
plt.title('Boxplot NPS entrega em tempo vs. atrasada')
plt.xlabel('Entrega atrasada')
plt.show()

"""Observamos uma média de 2.787 pontos NPS maior para pedidos entregues no prazo, com mediana 2.7 pontos acima também."""

# Taxa de recompra de clientes com pedidos que atrasaram.
print("Recompra de clientes com pedidos que atrasaram = " + str((df_delayed_delivery['repeat_purchase_30d'].sum() / len(df_delayed_delivery)) * 100))

# Taxa de recompra de clientes com pedidos que chegaram no tempo previsto.
print("Recompra de clientes com pedidos que chegaram no tempo previsto = " + str((df_ontime_delivery['repeat_purchase_30d'].sum() / len(df_ontime_delivery)) * 100))

"""Há uma queda na taxa de recompra de 28.357% devido ao atraso no prazo de entrega."""

print("Total de clientes que recompram, por cada categoria de atraso: \n" + str(df_nps.groupby('delay_category')['repeat_purchase_30d'].sum()))
print("Total de pedidos atrasados, por categoria: \n" + str(df_nps.groupby('delay_category')['customer_id'].count()))

"""Taxa de recompra por categoria de dias de atraso:

**No prazo** = 33.93%

**1 dia** = 14.79%

**2-3 dias** = 2.73%

**4-7 dias** = 0,23%

**7+ dias** = 0%
"""

# Grafico de linha que mostra o impacto de cada dia de atraso na média de NPS.
sns.lineplot(data=df_nps.groupby('delivery_delay_days')['nps_score'].mean().reset_index(), x='delivery_delay_days', y='nps_score', marker='o')

# Traça uma linha de referência exatamente no valor médio do NPS score.
plt.axhline(df_nps['nps_score'].mean(), linestyle='--', label='Média')

plt.title('Tendência atraso X nps_score médio')
plt.xlabel('Dias de atraso')
plt.ylabel('nps_score médio')
plt.grid(True)
plt.legend()
plt.show()

# nps_score médio agrupado por dia de atraso na entrega
df_nps.groupby('delivery_delay_days')['nps_score'].mean()

# Total de pedidos por categoria de entrega original.
df_nps.groupby('delivery_commit_category')['customer_id'].count()

# Total de reclamações por categoria de entrega original.
df_nps[df_nps['has_complaints'] == True].groupby('delivery_commit_category')['complaints_count'].sum()

"""## Análise do NPS por região"""

# Função para cálculo do teste de Kruskal–Wallis
def kruskal_wallis_test(df, group_col, value_col):
  """
  Recebe um Dataframe, o nome da coluna que contém o grupo sob análise, e a coluna do valor sendo avaliado.
  Calcula o teste Kruskal-Wallis e imprime o resultado.
  """
  group_list = [df[df[group_col] == val][value_col] for val in df[group_col].unique()]

  stat, p_value = kruskal(*group_list)

  print("Estatística H:", stat)
  print("p-valor:", p_value)

# Boxplot do NPS por região.
sns.boxplot(x='customer_region', y='nps_score', data=df_nps)
plt.title('Boxplot NPS por região')
plt.xlabel('Região')
plt.show()

# Cálculo de estatísticas descritivas sobre nps_score, para cada região.
df_nps.groupby('customer_region')['nps_score'].describe()

# Cálculo de estatísticas descritivas sobre dias atrasados, para cada região.
df_delayed_delivery.groupby('customer_region')['delivery_delay_days'].describe()

kruskal_wallis_test(df_nps, 'customer_region', 'nps_score')

"""NPS médio para cada região do Brasil é bem próximo.

**NPS médio mais alto na região Sul**, onde também tivemos maior número de compras.

**NPS médio mais baixo na região Centro-Oeste**, que também possui o menor número de registros.

Como nps_score não segue uma distribuição normal, para verificar significância estatística para variação de NPS por região, utilizamos o teste Kruskal-Wallis.

**Como o valor p calculado foi 0.4965 (muito maior que 0.05), não é possível rejeitar H0, portanto não verificamos significância estatística para variação de NPS por região.**

## Cruzamento customer_region X delivery_delay_days X nps_score
"""

# Constroi um mapa de calor para visualizar o impacto do número de dias em atraso no valor do NPS médio de cada região.
heatmap_data = df_nps.pivot_table(index='customer_region', columns='delay_category', values='nps_score', aggfunc='mean')

plt.figure(figsize=(12, 8))

sns.heatmap(
    heatmap_data,
    annot=True,       # Mostra o valor do NPS dentro de cada quadrado
    fmt=".1f",        # Formata para 1 casa decimal
    cmap="RdYlGn",    # Seleciona a escala de cores red, yellow, green
    center=9,         # Define 9 como ponto central, separando neutros de promotores.
    linewidths=.5    # Separa os quadrados do mapa com uma linha
    )

plt.title('Impacto do Atraso no NPS por Região', fontsize=16)
plt.xlabel('Dias de Atraso', fontsize=12)
plt.ylabel('Região', fontsize=12)
plt.show()

"""## Análise de reclamações"""

print("Total de pedidos com reclamação = " + str(len(df_nps[df_nps['has_complaints'] == True])))

print("Total de pedidos sem reclamação = " + str(len(df_nps[df_nps['has_complaints'] == False])))

# Grafico de barras para representar total de pedidos com reclamação.
bar_graphic = sns.barplot(data = df_nps.groupby('has_complaints')['customer_id'].count().reset_index(), x = 'has_complaints', y='customer_id')
bar_graphic.bar_label(bar_graphic.containers[0])
plt.title('Total de pedidos com vs. sem reclamação')
plt.xlabel('Reclamação registrada')
plt.ylabel('Total de pedidos')
plt.show()

# Total de detratores que não fizeram pelo menos uma reclamação
print("Numero de detratores que não fizeram reclamação = " + str(df_nps[(df_nps['has_complaints'] == False) & (df_nps['is_detractor'] == True)]['customer_id'].count()))

"""Dos clientes que não possuem reclamações, 4 (17,39%) são detratores."""

# Estatisticas descritivas do NPS de pedidos com reclamação.
df_nps[df_nps['has_complaints'] == True]['nps_score'].describe()

# Estatisticas descritivas do NPS de pedidos sem reclamação.
df_nps[df_nps['has_complaints'] == False]['nps_score'].describe()

# Boxplot do NPS entrega em tempo X atrasada.
sns.boxplot(x='has_complaints', y='nps_score', data=df_nps)
plt.title('Boxplot NPS para pedidos com vs. sem reclamação')
plt.xlabel('Reclamação registrada')
plt.show()

# Grafico de linha que mostra o impacto do número de reclamações na média de NPS.
sns.lineplot(data=df_nps.groupby('complaints_count')['nps_score'].mean().reset_index(), x='complaints_count', y='nps_score', marker='o')

# Traça uma linha de referência exatamente no valor médio do NPS score.
plt.axhline(df_nps['nps_score'].mean(), linestyle='--', label='Média')

plt.title('Tendência reclamações X nps_score médio')
plt.xlabel('Número de reclamações')
plt.ylabel('nps_score médio')
plt.grid(True)
plt.legend()
plt.show()

# Constroi um mapa de calor para visualizar o cruzamento de dias de atraso e número de reclamações no nps_score médio.
heatmap_data = df_nps.pivot_table(index='complaints_count', columns='delay_category', values='nps_score', aggfunc='mean')

plt.figure(figsize=(12, 8))

sns.heatmap(
    heatmap_data,
    annot=True,       # Mostra o valor do NPS dentro de cada quadrado
    fmt=".1f",        # Formata para 1 casa decimal
    cmap="RdYlGn",    # Seleciona a escala de cores red, yellow, green
    center=9,         # Define 9 como ponto central, separando neutros de promotores.
    linewidths=.5    # Separa os quadrados do mapa com uma linha
    )

plt.title('NPS médio por número de reclamações para cada categoria de atraso', fontsize=16)
plt.xlabel('Dias de Atraso', fontsize=12)
plt.ylabel('Número de reclamações', fontsize=12)
plt.show()

# Registros sem atraso e com total de reclamações igual a 10. Apenas 1, o que explica a anomalia observada no gráfico.
df_nps[(df_nps['delayed'] == False) & (df_nps['complaints_count'] == 10)]['nps_score']

# Relação de quantos pedidos cada categoria de estimativa de entrega original possui.
df_nps.groupby('delivery_commit_category')['customer_id'].count()

# Pedidos com reclamação, agrupados por categoria de entrega original e de atraso.
df_nps[(df_nps['has_complaints'] == True)].groupby(['delivery_commit_category','delay_category'])['customer_id'].count()

# Pedidos com promessa de entrega em até um dia, agrupados por categoria de atraso.
df_nps[(df_nps['delivery_commit_category'] == '1 dia') & (df_nps['delayed'] == True)].groupby('delay_category')['customer_id'].count()

"""Percebemos que todos os pedidos com promessa original de 1 dia de entrega possuem reclamação.

Nenhum desses pedidos com promessa de entrega em 1 dia cumpriram essa estimativa. Todos eles tiveram atraso.

Para as outras estimativas de entrega, todos aqueles sem reclamação foram entregues no prazo.
"""

# Taxa de recompra de clientes com nenhuma reclamação.
print("Taxa de recompra de clientes sem reclamação = " + str((df_nps[df_nps['has_complaints'] == False]['repeat_purchase_30d'].sum()/len(df_nps[df_nps['has_complaints'] == False])) * 100))

# Taxa de recompra de clientes com pelo menos uma reclamação.
print("Taxa de recompra de clientes com pelo menos uma reclamação = " + str((df_nps[df_nps['has_complaints'] == True]['repeat_purchase_30d'].sum()/len(df_nps[df_nps['has_complaints'] == True])) * 100))

"""Taxa de recompra 61.41% menor para clientes que fizeram pelo menos uma reclamação."""

# Média de reclamações para pedidos atrasados, agrupados por categoria de atraso.
df_nps[(df_nps['has_complaints'] == True)].groupby('delay_category')['complaints_count'].describe()

"""## Análise de atendimento ao cliente"""

print("Clientes que contataram o atendimento, tiveram reclamação e não tiveram atraso na entrega: " + str(df_nps[(df_nps['contacted_support'] == True) & (df_nps['has_complaints'] == True) & (df_nps['delayed'] == False)]['customer_id'].count()))
print("Desse número, quantos repetiram a compra no período de 30 dias? " + str(df_nps[(df_nps['contacted_support'] == True) & (df_nps['has_complaints'] == True) & (df_nps['delayed'] == False) & (df_nps['repeat_purchase_30d'] == 1)]['customer_id'].count()))

"""75,94% dos clientes que contataram atendimento ao cliente e não tiveram atraso na entrega não voltaram a comprar após 30 dias"""

# NPS médio de clientes que contataram atendimento ao cliente, têm reclamação e não tiveram atraso.
df_nps[(df_nps['contacted_support'] == True) & (df_nps['has_complaints'] == True) & (df_nps['delayed'] == False)].groupby(['customer_service_contacts', 'resolution_time_days'])['nps_score'].mean()

"""Visando reduzir o número de detratores, o esforço deve ser para resolução de problemas no primeiro contato do cliente.

No primeiro contato, temos até 5 dias para resolução até que o cliente se torne um detrator.

A partir do segundo contato, mesmo com resolução no mesmo dia, em média ele já se tornou detrator.
"""